version: '3.4'

services:
  raspberry-projector:
    build:
      context: .
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "2345:2345"
    expose:
      - "2345"